name: golden_voice_app
description: Voice Room Party App with Fruit Game and Admin Panel.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_database: ^4.4.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.0.1
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
